### ISSUE TITLE
Thumbnails not loading

### ISSUE THREAD

**Issue by Kane-PhiloSoftware** [banthagroup/fslightbox-vue#90]
I am loading thumbnails from an external source. I have an issue where the thumbnails will not displayed, and a loading image will always be shown. Closing and re-opening the gallery will show thumbs once they have been loaded.

```
  lightboxFirstOpen = true;
  lightboxOpened() {
    this.savedScrollPosition = window.scrollY
    this.$router.push({
      hash: `gallery-${this.SlideNumber}`
    })
    if(this.lightboxFirstOpen){
      this.lightboxFirstOpen = false;
      var test = setTimeout(() => {
        this.lightboxKey = this.lightboxKey + "-updated";
        this.$nextTick(() => {
            this.Toggler = !this.Toggler;
        })
      }, 3000)
    }
  }
```

As a not ideal workaround, I can update the key after a long period of time in the hopes that the images are loaded. How can I ensure that thumbs get displayed as they load? Or at least, how can I confirm that all the images have loaded so I can update the key at a more appropriate time?

**Comment by jcampbell-cfn** [comment]
Circling back to this: there are lots of other problems with this library, and I don't recommend that anyone use it for any reason, it's been a huge waste of time for me.

**Comment by Kane-PhiloSoftware** [comment]
Do you have any other suggestions? I would like to move away from this for my current client, but hearing real feedback is always helpful.

**Comment by jcampbell-cfn** [comment]
I'm looking into replacements now, I'll let you know if there's one that stands out as good.

**Comment by jcampbell-cfn** [comment]
https://onycat.com/vue-easy-lightbox/

This one appears to be working. Really quick to adapt my wrapper component to use it instead, and it doesn't have any issues with race conditions. The developer is active on Github issues (last commented 3 days ago) and is maintaining both Vue3 and Vue2 versions. Seems like everything I wanted out of this library, a quick and simple lightbox you can just drop into a project.

**Comment by Kane-PhiloSoftware** [comment]
My man! I'll definitely take a further look into it and hopefully I can convince the client for a switch in the near future.

**Comment by Titoine** [comment]
If anyone want a quick hack and is not bothered to show thumbnails while they charge:
```css
// Fix bug: when switching between portrait and landscape images, thumbnail is not displayed and loader is displayed.
// Force show thumbnails
.fslightboxtw{
  opacity: 100 !important;
}
// Force hide the loader
.fslightboxl {
  display: none !important;
}

// Set your thumbnails width to avoid layout shift when images loads.
.fslightboxtw{
  min-width: 113px !important;
}
```
